# Generated by Django 4.0.5 on 2022-07-09 08:31

import apps.profiles.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=46, unique=True)),
                ('avatar', models.ImageField(upload_to=apps.profiles.models.upload_avatar_to)),
                ('bio', models.TextField()),
                ('profile_type', models.CharField(choices=[('BUS', 'Business'), ('USR', 'User')], max_length=3)),
                ('course', models.CharField(blank=True, max_length=60, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='born on')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='the public email')),
                ('public_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='link to twitter account')),
                ('twitter_username', models.CharField(blank=True, max_length=20, null=True, verbose_name='twitter handle')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='link to facebook account')),
                ('facebook_username', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='link to instagram account')),
                ('instagram_username', models.CharField(blank=True, max_length=20, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='campuses.campus')),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.profiles.models.upload_photo_to)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'db_table': 'featured_profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
