# Generated by Django 4.0.5 on 2022-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
