# Generated by Django 4.0.5 on 2022-06-24 23:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'role',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=45, unique=True)),
                ('avatar', models.ImageField(upload_to=apps.people.models.upload_avatar_to)),
                ('bio', models.TextField()),
                ('course', models.CharField(blank=True, max_length=60, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='born on')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='the public email')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='link to twitter account')),
                ('twitter_username', models.CharField(blank=True, max_length=20, null=True, verbose_name='twitter handle')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='link to facebook account')),
                ('facebook_username', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='link to instagram account')),
                ('instagram_username', models.CharField(blank=True, max_length=20, null=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='campuses.campus')),
                ('main_role', models.ForeignKey(help_text="The main role of the profile's owner in relation to the website, ie Admin, Founder, Sponsor", on_delete=django.db.models.deletion.PROTECT, related_name='main_profiles', to='people.role')),
                ('roles', models.ManyToManyField(blank=True, to='people.role', verbose_name="Other roles for this profile's owner")),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.profile')),
            ],
            options={
                'db_table': 'featured_profile',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
