# Generated by Django 4.0.5 on 2022-06-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roles',
            new_name='other_roles',
        ),
    ]
