# Generated by Django 4.0.5 on 2022-07-10 12:54

import apps.entertainment.models
import django.core.validators
from django.db import migrations, models
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('cinema_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cinema',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnTV',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_tv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('poster', models.ImageField(upload_to=apps.entertainment.models.upload_poster_to)),
                ('trailer', embed_video.fields.EmbedVideoField()),
                ('about', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(help_text='The movie or serie rating in percentage', validators=[django.core.validators.MinValueValidator(limit_value=0, message="Rating can't be less than 0%"), django.core.validators.MaxValueValidator(limit_value=100, message="Rating can't be more than 100%")])),
                ('in_cinema', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='entertainment.category')),
                ('cinemas', models.ManyToManyField(blank=True, to='entertainment.cinema')),
            ],
            options={
                'db_table': 'on_tv',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
