# Generated by Django 4.0.5 on 2022-06-28 07:14

import apps.articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('thumb_nail', models.ImageField(upload_to=apps.articles.models.upload_thumb_nail_to)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('SP', 'Suspended'), ('UN', 'Unpublished')], max_length=2)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='articles', to='articles.tag')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-created_at'],
                'permissions': [('can_publish_an_article', 'Can publish an article'), ('can_mark_article_as_featured', 'Can mark article as featured')],
                'abstract': False,
            },
        ),
    ]
